In [1]:
# utilizado para manejos de directorios y rutas
import os

# Computacion vectorial y cientifica para python
import numpy as np

# Librerias para graficación (trazado de gráficos)
from matplotlib import pyplot
from mpl_toolkits.mplot3d import Axes3D  # Necesario para graficar superficies 3D

# llama a matplotlib a embeber graficas dentro de los cuadernillos
%matplotlib inline

In [2]:
import pandas as pd
from sklearn.preprocessing import LabelEncoder
from datetime import datetime

In [3]:
#Carga de dataset
data = pd.read_csv('Smart watch prices.csv')

In [4]:
print(data)

        Brand           Model Operating System                Connectivity  \
0       Apple  Watch Series 7          watchOS  Bluetooth, Wi-Fi, Cellular   
1     Samsung  Galaxy Watch 4          Wear OS  Bluetooth, Wi-Fi, Cellular   
2      Garmin          Venu 2        Garmin OS            Bluetooth, Wi-Fi   
3      Fitbit         Versa 3        Fitbit OS            Bluetooth, Wi-Fi   
4      Fossil           Gen 6          Wear OS            Bluetooth, Wi-Fi   
..        ...             ...              ...                         ...   
374  Withings       ScanWatch      Withings OS            Bluetooth, Wi-Fi   
375      Zepp               Z          Zepp OS  Bluetooth, Wi-Fi, Cellular   
376     Honor    Watch GS Pro          Lite OS            Bluetooth, Wi-Fi   
377      Oppo      Watch Free          ColorOS            Bluetooth, Wi-Fi   
378  TicWatch           Pro 3          Wear OS  Bluetooth, Wi-Fi, Cellular   

    Display Type  Display Size (inches) Resolution Water Resist

In [5]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 379 entries, 0 to 378
Data columns (total 13 columns):
 #   Column                     Non-Null Count  Dtype  
---  ------                     --------------  -----  
 0   Brand                      378 non-null    object 
 1   Model                      378 non-null    object 
 2   Operating System           376 non-null    object 
 3   Connectivity               378 non-null    object 
 4   Display Type               377 non-null    object 
 5   Display Size (inches)      376 non-null    float64
 6   Resolution                 375 non-null    object 
 7   Water Resistance (meters)  378 non-null    object 
 8   Battery Life (days)        378 non-null    object 
 9   Heart Rate Monitor         378 non-null    object 
 10  GPS                        378 non-null    object 
 11  NFC                        378 non-null    object 
 12  Price (USD)                378 non-null    object 
dtypes: float64(1), object(12)
memory usage: 38.6+ KB


In [6]:
columnas_eliminar = ['Price (USD)']
simbolo = '$'

for columna in columnas_eliminar:
    data[columna] = data[columna].str.replace(simbolo, '', regex=False)

In [7]:
print(data)

        Brand           Model Operating System                Connectivity  \
0       Apple  Watch Series 7          watchOS  Bluetooth, Wi-Fi, Cellular   
1     Samsung  Galaxy Watch 4          Wear OS  Bluetooth, Wi-Fi, Cellular   
2      Garmin          Venu 2        Garmin OS            Bluetooth, Wi-Fi   
3      Fitbit         Versa 3        Fitbit OS            Bluetooth, Wi-Fi   
4      Fossil           Gen 6          Wear OS            Bluetooth, Wi-Fi   
..        ...             ...              ...                         ...   
374  Withings       ScanWatch      Withings OS            Bluetooth, Wi-Fi   
375      Zepp               Z          Zepp OS  Bluetooth, Wi-Fi, Cellular   
376     Honor    Watch GS Pro          Lite OS            Bluetooth, Wi-Fi   
377      Oppo      Watch Free          ColorOS            Bluetooth, Wi-Fi   
378  TicWatch           Pro 3          Wear OS  Bluetooth, Wi-Fi, Cellular   

    Display Type  Display Size (inches) Resolution Water Resist

In [8]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 379 entries, 0 to 378
Data columns (total 13 columns):
 #   Column                     Non-Null Count  Dtype  
---  ------                     --------------  -----  
 0   Brand                      378 non-null    object 
 1   Model                      378 non-null    object 
 2   Operating System           376 non-null    object 
 3   Connectivity               378 non-null    object 
 4   Display Type               377 non-null    object 
 5   Display Size (inches)      376 non-null    float64
 6   Resolution                 375 non-null    object 
 7   Water Resistance (meters)  378 non-null    object 
 8   Battery Life (days)        378 non-null    object 
 9   Heart Rate Monitor         378 non-null    object 
 10  GPS                        378 non-null    object 
 11  NFC                        378 non-null    object 
 12  Price (USD)                378 non-null    object 
dtypes: float64(1), object(12)
memory usage: 38.6+ KB


In [9]:

# Supongamos que 'data' es tu DataFrame
columna_categorica = 'Price (USD)'
columna_numerica = 'Price'

# Crea una nueva columna numérica y copia los valores de la columna categórica
data[columna_numerica] = pd.to_numeric(data[columna_categorica], errors='coerce')

# Elimina la columna categórica original
data.drop(columna_categorica, axis=1, inplace=True)

In [10]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 379 entries, 0 to 378
Data columns (total 13 columns):
 #   Column                     Non-Null Count  Dtype  
---  ------                     --------------  -----  
 0   Brand                      378 non-null    object 
 1   Model                      378 non-null    object 
 2   Operating System           376 non-null    object 
 3   Connectivity               378 non-null    object 
 4   Display Type               377 non-null    object 
 5   Display Size (inches)      376 non-null    float64
 6   Resolution                 375 non-null    object 
 7   Water Resistance (meters)  378 non-null    object 
 8   Battery Life (days)        378 non-null    object 
 9   Heart Rate Monitor         378 non-null    object 
 10  GPS                        378 non-null    object 
 11  NFC                        378 non-null    object 
 12  Price                      372 non-null    float64
dtypes: float64(2), object(11)
memory usage: 38.6+ KB


In [11]:
#variables categoricas
columnas_categoricas = data.select_dtypes(include=['object']).columns
#variables fechas
columnas_fechas = data.select_dtypes(include=['datetime64']).columns

In [12]:
#Procesamiento de frases o palabras
for columna in columnas_categoricas:
  le = LabelEncoder()
  data[columna] = le.fit_transform(data[columna])

In [13]:
#Fechas a numeros
for columna in columnas_fechas:
  data[columna] = pd.to_numeric(data[columna].map(datetime.timestamp))

In [14]:
#resultado
print(data)

     Brand  Model  Operating System  Connectivity  Display Type  \
0        1    127                34             2            17   
1       30     36                31             2             0   
2        8    105                 9             1             0   
3        6    109                 7             1             0   
4        7     43                31             1             0   
..     ...    ...               ...           ...           ...   
374     38     79                32             1            16   
375     41    132                33             2             0   
376      9    119                12             1             0   
377     26    118                 5             1             0   
378     35     71                31             2             0   

     Display Size (inches)  Resolution  Water Resistance (meters)  \
0                     1.90          27                          5   
1                     1.40          31                   

In [15]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 379 entries, 0 to 378
Data columns (total 13 columns):
 #   Column                     Non-Null Count  Dtype  
---  ------                     --------------  -----  
 0   Brand                      379 non-null    int32  
 1   Model                      379 non-null    int32  
 2   Operating System           379 non-null    int32  
 3   Connectivity               379 non-null    int32  
 4   Display Type               379 non-null    int32  
 5   Display Size (inches)      376 non-null    float64
 6   Resolution                 379 non-null    int32  
 7   Water Resistance (meters)  379 non-null    int32  
 8   Battery Life (days)        379 non-null    int32  
 9   Heart Rate Monitor         379 non-null    int32  
 10  GPS                        379 non-null    int32  
 11  NFC                        379 non-null    int32  
 12  Price                      372 non-null    float64
dtypes: float64(2), int32(11)
memory usage: 22.3 KB


In [16]:
#llenar datos vacios
columnas_especificas = ['Price', 'Display Size (inches)']
media_columnas = data[columnas_especificas].mean()
data[columnas_especificas] = data[columnas_especificas].fillna(media_columnas)

In [17]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 379 entries, 0 to 378
Data columns (total 13 columns):
 #   Column                     Non-Null Count  Dtype  
---  ------                     --------------  -----  
 0   Brand                      379 non-null    int32  
 1   Model                      379 non-null    int32  
 2   Operating System           379 non-null    int32  
 3   Connectivity               379 non-null    int32  
 4   Display Type               379 non-null    int32  
 5   Display Size (inches)      379 non-null    float64
 6   Resolution                 379 non-null    int32  
 7   Water Resistance (meters)  379 non-null    int32  
 8   Battery Life (days)        379 non-null    int32  
 9   Heart Rate Monitor         379 non-null    int32  
 10  GPS                        379 non-null    int32  
 11  NFC                        379 non-null    int32  
 12  Price                      379 non-null    float64
dtypes: float64(2), int32(11)
memory usage: 22.3 KB


In [18]:
# Lectura de Datos
X = data.iloc[:, :12]
y = data.iloc[:, 12]
m = y.size

In [19]:
print(X)
print('*'*25)
print(y)

     Brand  Model  Operating System  Connectivity  Display Type  \
0        1    127                34             2            17   
1       30     36                31             2             0   
2        8    105                 9             1             0   
3        6    109                 7             1             0   
4        7     43                31             1             0   
..     ...    ...               ...           ...           ...   
374     38     79                32             1            16   
375     41    132                33             2             0   
376      9    119                12             1             0   
377     26    118                 5             1             0   
378     35     71                31             2             0   

     Display Size (inches)  Resolution  Water Resistance (meters)  \
0                     1.90          27                          5   
1                     1.40          31                   

In [20]:
# Añade el termino de interseccion a X
# (Columna de unos para X0)
X = np.concatenate([np.ones((m, 1)), X], axis=1)

In [21]:
print(X)

[[  1.   1. 127. ...   0.   1.   1.]
 [  1.  30.  36. ...   0.   1.   1.]
 [  1.   8. 105. ...   0.   1.   0.]
 ...
 [  1.   9. 119. ...   0.   1.   1.]
 [  1.  26. 118. ...   0.   0.   1.]
 [  1.  35.  71. ...   0.   1.   1.]]


In [22]:
X_array = [1, 2, 130, 32, 1, 17, 1.48, 29, 4, 12, 0, 1, 1]

In [23]:
X_array[1:13]

[2, 130, 32, 1, 17, 1.48, 29, 4, 12, 0, 1, 1]

In [24]:
def normalEqn(X, y):

    theta = np.zeros(X.shape[1])

    theta = np.dot(np.dot(np.linalg.inv(np.dot(X.T,X)),X.T),y)

    return theta

In [25]:
# Calcula los parametros con la ecuación de la normal
theta = normalEqn(X, y);

# Muestra los resultados optenidos a partir de la aplicación de la ecuación de la normal
print('Theta calculado a partir de la ecuación de la normal: {:s}'.format(str(theta)));

# Estimar el precio para una casa de superficie de 1650 sq-ft y tres dormitorios

X_array = [1, 2, 130, 32, 1, 17, 1.48, 29, 4, 12, 0, 1, 1]
price = np.dot(X_array, theta)

print('Precio predecido para una cada de superficie de 1650 sq-ft y 3 dormitorios (usando la ecuación de la normal): ${:.0f}'.format(price))

Theta calculado a partir de la ecuación de la normal: [351.41756009  -1.73375963  -0.63918384   1.5095825   19.69057974
   3.38618598  83.30479077  -2.43386481 -49.00284191  -2.58375784
 -29.85108901 130.21313908  12.64119062]
Precio predecido para una cada de superficie de 1650 sq-ft y 3 dormitorios (usando la ecuación de la normal): $359
